// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: FinishCommand.sql

package db

import (
	"context"

	"time"
)

const finishCommand = `-- name: FinishCommand :exec
update history
set duration = ?, exit = ?
where id = ?
`

type FinishCommandParams struct {
	Duration time.Duration `json:"duration"`
	Exit     int64         `json:"exit"`
	ID       int64         `json:"id"`
}

// Updates the command initially inserted by StartCommand
// populating duration and exit. Run from the post-exec hook once
// the command's duration and exit code are known.
func (q *Queries) FinishCommand(ctx context.Context, arg FinishCommandParams) error {
	_, err := q.db.ExecContext(ctx, finishCommand, arg.Duration, arg.Exit, arg.ID)
	return err
}
