// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidates.sql

package db

import (
	"context"
)

const listCandidates = `-- name: ListCandidates :many
SELECT id, cmd, cwd, session, started_at, duration, exit
FROM history
WHERE
    id IN (
        SELECT max(h.id) FROM history h
        GROUP BY h.cmd
    )
ORDER BY started_at DESC
LIMIT ?
`

// Fetches N unique history entries scoped globally, i.e. not bound by session
// or current directory.
func (q *Queries) ListCandidates(ctx context.Context, limit int64) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Cmd,
			&i.Cwd,
			&i.Session,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
