// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidatesInSession.sql

package db

import (
	"context"
)

const listCandidatesInSession = `-- name: ListCandidatesInSession :many
SELECT id, cmd, cwd, session, started_at, duration, exit
FROM history
WHERE
    id IN (
        SELECT max(h.id) FROM history h
        WHERE h.session = ?
        GROUP BY h.cmd
    )
ORDER BY started_at DESC
LIMIT ?
`

type ListCandidatesInSessionParams struct {
	Session string `json:"session"`
	Limit   int64  `json:"limit"`
}

// Fetches N unique history entries, scoped to the current session.
func (q *Queries) ListCandidatesInSession(ctx context.Context, arg ListCandidatesInSessionParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesInSession, arg.Session, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Cmd,
			&i.Cwd,
			&i.Session,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
