// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidatesInSession.sql

package db

import (
	"context"
	"time"
)

const listCandidatesInSession = `-- name: ListCandidatesInSession :many
select
    cmd,
    cwd,
    started_at,
    duration,
    exit
from history
where session = ?
order by started_at desc
limit ?
`

type ListCandidatesInSessionParams struct {
	Session string `json:"session"`
	Limit   int64  `json:"limit"`
}

type ListCandidatesInSessionRow struct {
	Cmd       string        `json:"cmd"`
	Cwd       string        `json:"cwd"`
	StartedAt time.Time     `json:"started_at"`
	Duration  time.Duration `json:"duration"`
	Exit      int64         `json:"exit"`
}

// Fetches N history entries, scoped to the current session.
func (q *Queries) ListCandidatesInSession(ctx context.Context, arg ListCandidatesInSessionParams) ([]ListCandidatesInSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesInSession, arg.Session, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesInSessionRow
	for rows.Next() {
		var i ListCandidatesInSessionRow
		if err := rows.Scan(
			&i.Cmd,
			&i.Cwd,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
