// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidatesInDirectory.sql

package db

import (
	"context"
)

const listCandidatesInDirectory = `-- name: ListCandidatesInDirectory :many
select id, cmd, cwd, session, started_at, duration, exit
from history
where
    id in (
        select max(h.id) from history h
        where h.cwd = ?
        group by h.cmd
    )
order by started_at desc
limit ?
`

type ListCandidatesInDirectoryParams struct {
	Cwd   string `json:"cwd"`
	Limit int64  `json:"limit"`
}

// Fetches N history entries scoped to the current directory only.
func (q *Queries) ListCandidatesInDirectory(ctx context.Context, arg ListCandidatesInDirectoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesInDirectory, arg.Cwd, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Cmd,
			&i.Cwd,
			&i.Session,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
