// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidatesInDirectory.sql

package db

import (
	"context"
	"time"
)

const listCandidatesInDirectory = `-- name: ListCandidatesInDirectory :many
select
    cmd,
    cwd,
    started_at,
    duration,
    exit
from history
where
    id in (
        select max(h.id) from history h
        where h.cwd = ?
        group by h.cmd
    )
order by started_at desc
limit ?
`

type ListCandidatesInDirectoryParams struct {
	Cwd   string `json:"cwd"`
	Limit int64  `json:"limit"`
}

type ListCandidatesInDirectoryRow struct {
	Cmd       string        `json:"cmd"`
	Cwd       string        `json:"cwd"`
	StartedAt time.Time     `json:"started_at"`
	Duration  time.Duration `json:"duration"`
	Exit      int64         `json:"exit"`
}

// Fetches N history entries scoped to the current directory only.
func (q *Queries) ListCandidatesInDirectory(ctx context.Context, arg ListCandidatesInDirectoryParams) ([]ListCandidatesInDirectoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesInDirectory, arg.Cwd, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesInDirectoryRow
	for rows.Next() {
		var i ListCandidatesInDirectoryRow
		if err := rows.Scan(
			&i.Cmd,
			&i.Cwd,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
