// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ListCandidates.sql

package db

import (
	"context"
	"time"
)

const listCandidates = `-- name: ListCandidates :many
select
    cmd,
    cwd,
    started_at,
    duration,
    exit
from history
where
    id in (
        select max(id) from history
        group by cmd
    )
order by started_at desc
limit ?
`

type ListCandidatesRow struct {
	Cmd       string        `json:"cmd"`
	Cwd       string        `json:"cwd"`
	StartedAt time.Time     `json:"started_at"`
	Duration  time.Duration `json:"duration"`
	Exit      int64         `json:"exit"`
}

// Fetches N history entries scoped globally, i.e. not bound by session
// or current directory.
func (q *Queries) ListCandidates(ctx context.Context, limit int64) ([]ListCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.Cmd,
			&i.Cwd,
			&i.StartedAt,
			&i.Duration,
			&i.Exit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
