// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type History struct {
	ID        int64         `json:"id"`
	Cmd       string        `json:"cmd"`
	Cwd       string        `json:"cwd"`
	Session   string        `json:"session"`
	StartedAt time.Time     `json:"started_at"`
	Duration  time.Duration `json:"duration"`
	Exit      int64         `json:"exit"`
}
