// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Updates the command initially inserted by StartCommand
	// populating duration and exit. Run from the post-exec hook once
	// the command's duration and exit code are known.
	FinishCommand(ctx context.Context, arg FinishCommandParams) error
	// Fetches N history entries scoped globally, i.e. not bound by session
	// or current directory.
	ListCandidates(ctx context.Context, limit int64) ([]History, error)
	// Fetches N history entries scoped to the current directory only.
	ListCandidatesInDirectory(ctx context.Context, arg ListCandidatesInDirectoryParams) ([]History, error)
	// Fetches N history entries, scoped to the current session.
	ListCandidatesInSession(ctx context.Context, arg ListCandidatesInSessionParams) ([]History, error)
	// Inserts the command from the pre-exec hook, before duration
	// and exit are known. Returns the id so FinishCommand can
	// update it with exit and duration.
	StartCommand(ctx context.Context, arg StartCommandParams) (int64, error)
	// Fetches the most recently started command matching the given
	// prefix. Used to power shell autosuggestion.
	SuggestByPrefix(ctx context.Context, prefix string) (string, error)
}

var _ Querier = (*Queries)(nil)
