// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StartCommand.sql

package db

import (
	"context"
	"time"
)

const startCommand = `-- name: StartCommand :one
INSERT INTO history (cmd, cwd, session, started_at)
VALUES (?, ?, ?, ?)
RETURNING id
`

type StartCommandParams struct {
	Cmd       string    `json:"cmd"`
	Cwd       string    `json:"cwd"`
	Session   string    `json:"session"`
	StartedAt time.Time `json:"started_at"`
}

// Inserts the command from the pre-exec hook, before duration
// and exit are known. Returns the id so FinishCommand can
// update it with exit and duration.
func (q *Queries) StartCommand(ctx context.Context, arg StartCommandParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, startCommand,
		arg.Cmd,
		arg.Cwd,
		arg.Session,
		arg.StartedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
