// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: SuggestByPrefix.sql

package db

import (
	"context"
)

const suggestByPrefix = `-- name: SuggestByPrefix :one
SELECT cmd
FROM history
WHERE
    cmd >= ?1
    AND cmd < ?1 || char(1114111)
ORDER BY started_at DESC
LIMIT 1
`

// Fetches the most recently started command matching the given
// prefix. Used to power shell autosuggestion.
func (q *Queries) SuggestByPrefix(ctx context.Context, prefix string) (string, error) {
	row := q.db.QueryRowContext(ctx, suggestByPrefix, prefix)
	var cmd string
	err := row.Scan(&cmd)
	return cmd, err
}
