// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: SuggestByPrefix.sql

package db

import (
	"context"
)

const suggestByPrefix = `-- name: SuggestByPrefix :one
select cmd
from history
where instr(cmd, ?1) = 1
order by started_at desc
limit 1
`

// Fetches the most recently started command matching the given
// prefix. Used to power shell autosuggestion.
func (q *Queries) SuggestByPrefix(ctx context.Context, prefix string) (string, error) {
	row := q.db.QueryRowContext(ctx, suggestByPrefix, prefix)
	var cmd string
	err := row.Scan(&cmd)
	return cmd, err
}
